### ISSUE TITLE
IAM userName error 

### ISSUE THREAD

**Issue by stephencoe** [mmmorris1975/aws-runas#21]
Hey @mmmorris1975 👋 

I was just testing the new version and it appears to throw an error with the same usage that worked in the previous version I had installed `1.0.0`

## Command 
```
 ~/Downloads  AWS_PROFILE=sandbox aws-runas -D -v s3 ls
aws-runas.main 2018/08/16 13:00:30 [DEBU] ▶ PROFILE: sandbox
Assume Role MFA token code: XXXXXX
aws-runas.main 2018/08/16 13:00:37 [WARN] ▶ Error getting IAM user info: ValidationError: Must specify userName when calling with non-User credentials
	status code: 400, request id: fce84685-a14b-11e8-a654-877eba206c85
aws-runas.main 2018/08/16 13:00:37 [DEBU] ▶ Diagnostics
SharedCfgConfigHandler 2018/08/16 13:00:37 [DEBU] ▶ Section 'sandbox' not found, trying 'profile sandbox'
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x1491d22]

goroutine 1 [running]:
main.awsProfile(0x166e200, 0xc4200656f0, 0xc4200281cc, 0x7, 0x0, 0x0, 0xc420153ca0, 0x1012bb8)
	/Users/morrm1/go/src/github.com/mmmorris1975/aws-runas/main.go:400 +0x2d2
main.main()
	/Users/morrm1/go/src/github.com/mmmorris1975/aws-runas/main.go:163 +0x1246
 ~/Downloads  AWS_PROFILE=sandbox aws-runas -D -v -l                                                                                          ✘
aws-runas.main 2018/08/16 13:02:21 [DEBU] ▶ PROFILE: sandbox
Assume Role MFA token code: 416611
aws-runas.main 2018/08/16 13:02:29 [WARN] ▶ Error getting IAM user info: ValidationError: Must specify userName when calling with non-User credentials
	status code: 400, request id: 3fa5d91c-a14c-11e8-bd19-47d1c1f71cf5
aws-runas.main 2018/08/16 13:02:29 [CRIT] ▶ Unable to determine IAM user
```

Is there something additional required in the config or an internal error?

**Comment by mmmorris1975** [comment]
Double check that you don't already have AWS credentials set via environment variables.  That error is likely seen because there are credentials set somewhere which aren't your (personal) IAM user credentials.

**Comment by stephencoe** [comment]
Hi @mmmorris1975 , thanks for looking at this originally. I have tested this again and still the same issue. I have confirmed there are no AWS related environment variables. I am trying understand the flow better so I can atleast work out where this has become a problem

```
 ~/Downloads  AWS_PROFILE=sandbox ./aws-runas aws s3 ls                                                                                                                                   ✘
Assume Role MFA token code: 045845
aws-runas.main 2018/09/24 16:03:04 [WARN] ▶ Error getting IAM user info, retrying with AWS credential env vars unset
Assume Role MFA token code: 167749
aws-runas.main 2018/09/24 16:03:34 [WARN] ▶ Error getting IAM user info: ValidationError: Must specify userName when calling with non-User credentials
	status code: 400, request id: 01ce9874-c00b-11e8-8095-4f644b01fa4d
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x1491c32]

goroutine 1 [running]:
main.awsProfile(0x166e280, 0xc4200af6a0, 0xc4200281ec, 0x7, 0x0, 0x1, 0xc4200c6101, 0xc4200c6178)
	/Users/morrm1/go/src/github.com/mmmorris1975/aws-runas/main.go:384 +0x2d2
main.main()
	/Users/morrm1/go/src/github.com/mmmorris1975/aws-runas/main.go:193 +0x915
```
